<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <AssemblyName>com.github.MiiMii1205.PEAKSeating</AssemblyName>
        <AssemblyTitle>PEAKSeating</AssemblyTitle>
        <Version>0.1.0</Version>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Update="Hamunii.BepInEx.AutoPlugin" Version="*"/>
    </ItemGroup>

</Project>
